apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: jenkins.pipeline.rebaze.io
  dnsNames:
  - jenkins.pipeline.rebaze.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - jenkins.pipeline.rebaze.io