apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-jenkins
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: jenkins.pipeline.rebaze.io
    http:
      paths:
      - path: /
        backend:
          serviceName: my-release-jenkins
          servicePort: 8080