apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: toni.menzel@rebaze.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
    - selector:
        matchLabels:
          use-cloudflare-solver: "true"
      dns01:
        cloudflare:
          email: toni.menzel@rebaze.com
          apiKeySecretRef:
            name: cloudflare-apikey-secret
            key: apikey